version: 2.1
orbs:
  maven: circleci/maven@1.4.1
  snyk: snyk/snyk@1.7.0

jobs:
  maven_build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout 
      - run: mvn clean package
  snyk_sca:
    docker:
      - image: circleci/node:4.8.2

    steps:
      - checkout
      - run: npm install -q
      - snyk/install
      - snyk/scan

  maven_test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout 
      - run: mvn test


workflows: 
  build_test: 
    jobs:
      - maven_build
      - snyk_sca:
          requires:
           - maven_build
      - maven_test:
          requires:
           - snyk_sca