version: 2.1
orbs:
  maven: circleci/maven@1.4.1

jobs:
  maven_build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout 
      - run: mvn -B -DskipTests clean package


workflows: 
  build_now: 
    jobs:
      - maven_build