version: 2.1
orbs:
  maven: circleci/maven@1.4.1

jobs:
  maven_build:
    docker:
      - image: cimg/openjdk:20.0.1
    steps:
      - checkout 
      - run: 'mvn build'


workflows: 
  build_now: 
    jobs:
      - maven_build