version: 2.1
orbs:
  maven: circleci/maven@1.4.1

jobs:
  maven_build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout 
      - run: mvn clean package

  maven_test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout 
      - run: mvn test


workflows: 
  build_test: 
    jobs:
      - maven_build
      - maven_test:
          requires:
           - maven_build